import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiRedux,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiGit,
  SiGithub,
  SiJest,
  SiFigma,
  SiDocker,
  SiJira,
} from 'react-icons/si';

import { FaSass } from 'react-icons/fa';

import { Experience, Project, Skill, SocialLink, ContactInfo } from '@/types';

export const PERSONAL_INFO = {
  name: 'Hamza CHARAFI',
  role: 'Senior Front-End Developer - ReactJS',
  email: 'h.charafi@gmail.com',
  phone: '+33 6 30 47 10 42',
  location: 'Paris, France',
  yearsOfExperience: 9,
  projectsCompleted: 20,
  companiesWorked: 5,
  technologiesMastered: 35,
};

export const SOCIAL_LINKS: SocialLink[] = [
  {
    name: 'GitHub',
    url: 'https://github.com/hamzachar',
    icon: 'FaGithub',
  },
  {
    name: 'LinkedIn',
    url: 'https://www.linkedin.com/in/hamza-charafi-93b91510a/',
    icon: 'FaLinkedin',
  },
  {
    name: 'Email',
    url: 'mailto:h.charafi@gmail.com',
    icon: 'FaEnvelope',
  },
];

export const EDUCATION = {
  degree: "Master's Degree",
  field: 'Computer Science and Information Systems',
  institution: 'FP BENI-MELLAL',
  year: '2016',
};

export const LANGUAGES = {
  french: 'Fluent',
  english: 'Intermediate',
};

export const CONTINUOUS_LEARNING = [
  'Udemy',
  'Egghead',
  'Frontend Masters',
  'Medium',
];

export const EXPERIENCES: Experience[] = [
  {
    id: 'ekino',
    company: 'Ekino',
    role: 'Senior Front-End Developer - React.js',
    period: 'March 2024 - Present',
    location: 'France',
    description:
      'Developed a web platform for product selection and search to optimize customer experience and facilitate access to technical solutions and specialty materials documentation.',
    achievements: [
      'Collaborated closely with operational teams to adapt interfaces to industrial site requirements',
      'Implemented complex user workflows for production data validation and quality control',
      'Developed complex interfaces for real-time production data visualization using React 18 and TypeScript',
      'Created advanced reusable components with modular and scalable architecture',
      'Optimized performance for processing large industrial datasets (lazy loading, memoization)',
      'Integrated REST APIs for data synchronization',
      'Implemented advanced patterns (HOC, Render Props, Custom Hooks) for code reusability',
      'Developed client-side caching logic to optimize performance',
      'Developed robust unit and integration tests using Jest and React-Testing-Library',
      'Actively participated in code reviews to maintain code quality and best practices',
    ],
    technologies: [
      'React',
      'TypeScript',
      'SASS',
      'Jest',
      'React-Testing-Library',
      'Docker',
      'Figma',
      'GitLab CI/CD',
      'GitFlow',
      'Webpack',
      'ESLint',
      'Prettier',
      'Storybook',
      'TanStack Query',
      'Playwright',
    ],
    logo: '/images/companies/ekino.png',
  },
  {
    id: 'reunion-aerienne',
    company: 'La Réunion Aérienne',
    role: 'Senior Front-End Developer React JS',
    period: 'September 2022 - February 2024',
    location: 'France',
    description:
      'Developed an application for automating contract management for agents and business developers.',
    achievements: [
      'Participated in scope meetings and technical direction discussions',
      'Analyzed and estimated User Stories for better task planning',
      'Actively engaged in SCRUM ceremonies and JIRA task tracking',
      'Integrated UX/UI mockups using Figma',
      'Developed user interfaces and reusable components with React.js',
      'Managed application state using Redux Toolkit',
      'Handled asynchronous requests with CreateAsyncThunk',
      'Proactively identified technical issues and proposed effective solutions',
      'Wrote unit tests using Jest and React-Testing-Library',
      'Conducted code reviews on every pull request',
      'Regularly practiced pair programming',
    ],
    technologies: [
      'React',
      'Redux-Toolkit',
      'Redux Thunk',
      'TypeScript',
      'SASS',
      'Jest',
      'React-Testing-Library',
      'Docker',
      'Figma',
      'GitLab CI/CD',
      'GitFlow',
    ],
    logo: '/images/companies/reunion.png',
  },
  {
    id: 'disneyland',
    company: 'Disneyland Paris',
    role: 'Front-End Developer ReactJS',
    period: 'August 2021 - August 2022',
    location: 'France',
    description:
      'Developed and maintained a booking application, including bug fixes and enhancements.',
    achievements: [
      'Analyzed technical and functional specifications',
      'Tracked tasks using Jira for efficient project management',
      'Maintained organized documentation on Confluence',
      'Actively participated in SAFe agile ceremonies',
      'Maintained and evolved application state management using Redux and Context API',
      'Integrated UX/UI mockups from Figma',
      'Created reusable components with React.js',
      'Implemented routing module using React Router',
      'Consumed GraphQL APIs with Apollo Client',
      'Implemented unit tests using Jest, Enzyme, and e2e tests using Cypress',
      'Conducted code reviews',
      'Regularly engaged in pair programming',
    ],
    technologies: [
      'React',
      'Redux',
      'Redux Thunk',
      'TypeScript',
      'Styled-Components',
      'GraphQL',
      'Apollo Client',
      'Jest',
      'Enzyme',
      'Cypress',
      'Figma',
      'GitLab CI/CD',
      'GitFlow',
      'Jira',
    ],
    logo: '/images/companies/disney.png',
  },
  {
    id: 'capgemini',
    company: 'Capgemini',
    role: 'Full-Stack Developer ReactJS / NodeJS',
    period: 'September 2018 - August 2021',
    location: 'France',
    description:
      'Developed and maintained scalable applications with continuous evolution and maintenance support.',
    achievements: [
      'Analyzed technical and functional specifications',
      'Tracked tasks using Jira for efficient project management',
      'Developed robust REST APIs using Express.js',
      'Implemented authentication management with JWT (JSON Web Tokens)',
      'Designed database models using Sequelize schemas',
      'Utilized Express.js middleware for authentication, data validation, and error handling',
      'Implemented data validation using express-validator for data integrity',
      'Identified and resolved performance issues using Redis caching',
      'Efficiently managed asynchronous requests using Redux Thunk',
      'Created dynamic routes using React Router',
      'Integrated UX/UI mockups from Figma',
      'Developed state management module using Redux',
      'Performed API testing using Postman',
      'Applied Clean Code best practices',
    ],
    technologies: [
      'React',
      'Redux',
      'Context API',
      'Node.js',
      'Express.js',
      'TypeScript',
      'Sequelize',
      'Mongoose',
      'Redis',
      'Styled-Components',
      'PostgreSQL',
      'MongoDB',
      'JWT',
      'GitLab CI/CD',
      'GitFlow',
      'Jira',
    ],
    logo: '/images/companies/capgemini.png',
  },
  {
    id: '2wls',
    company: '2WLS',
    role: 'Full-Stack Developer ReactJS / NodeJS',
    period: 'September 2016 - August 2018',
    location: 'France',
    description:
      'Developed loyalty solutions and growth marketing initiatives.',
    achievements: [
      'Analyzed detailed technical and functional specifications',
      'Participated in technical validation meetings',
      'Set up web server using Node.js and Express.js',
      'Developed and consumed REST APIs using Express.js',
      'Connected server to MySQL using Sequelize',
      'Developed models and generated tables via Sequelize',
      'Implemented authentication with JWT',
      'Contributed to developing a centralized loyalty system in Node.js and React.js',
      'Developed a "Raffle" microservice for participant rewards using Express.js and Redis',
      'Managed state and asynchronous requests with Redux',
      'Integrated UX/UI mockups from Figma',
      'Designed components and pages for Gifts, Contact Us, Footer, Menus, Forms',
      'Developed navigation module using React Router',
      'Performed API testing using Postman',
    ],
    technologies: [
      'React',
      'Redux',
      'Redux Thunk',
      'TypeScript',
      'Styled-Components',
      'Node.js',
      'Express.js',
      'MySQL',
      'Sequelize',
      'Redis',
      'JWT',
      'Axios',
      'Jest',
      'Figma',
      'GitLab CI/CD',
      'GitFlow',
      'Jira',
      'Postman',
    ],
    logo: '/images/companies/2wls.png',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'disney-booking-app',
    title: 'Disney Booking App',
    description:
      'A booking application for Disney parks with real-time availability, user authentication, and payment integration.',
    image: '/images/projects/disney-booking.png',
    technologies: ['React', 'TypeScript', 'styled-components', 'Stripe', '...'],
    liveUrl: 'https://book.disneylandparis.com/',
    githubUrl: '#',
    featured: true,
  },
  {
    id: 'arkema-platform',
    title: 'Arkema Industrial Platform',
    description:
      'A web platform for product selection and search to optimize customer experience and facilitate access to technical solutions and specialty materials documentation.',
    image: '/images/projects/arkema.png',
    technologies: ['React', 'TypeScript', 'SCSS', 'Storybook', '...'],
    liveUrl: 'https://www.arkema.com/',
    githubUrl: '#',
    featured: true,
  },
  {
    id: 'portfolio-template',
    title: 'My Portfolio Template',
    description:
      'Modern, responsive portfolio template with animations, dark mode, and internationalization support.',
    image: '',
    technologies: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'next-intl',
      '...',
    ],
    liveUrl: '#',
    githubUrl: 'https://github.com/hamzachar',
    featured: false,
  },
];

export const SKILLS: Skill[] = [
  // Frontend
  {
    name: 'React.js',
    level: 95,
    category: 'frontend',
    icon: SiReact,
    color: '#61DAFB',
  },
  {
    name: 'Next.js',
    level: 90,
    category: 'frontend',
    icon: SiNextdotjs,
    color: '#000000',
  },
  {
    name: 'TypeScript',
    level: 90,
    category: 'frontend',
    icon: SiTypescript,
    color: '#3178C6',
  },
  {
    name: 'JavaScript',
    level: 95,
    category: 'frontend',
    icon: SiJavascript,
    color: '#F7DF1E',
  },
  {
    name: 'Redux',
    level: 85,
    category: 'frontend',
    icon: SiRedux,
    color: '#764ABC',
  },
  {
    name: 'HTML5',
    level: 95,
    category: 'frontend',
    icon: SiHtml5,
    color: '#E34F26',
  },
  {
    name: 'CSS3',
    level: 90,
    category: 'frontend',
    icon: SiCss3,
    color: '#1572B6',
  },
  {
    name: 'Tailwind CSS',
    level: 90,
    category: 'frontend',
    icon: SiTailwindcss,
    color: '#06B6D4',
  },
  {
    name: 'Sass',
    level: 85,
    category: 'frontend',
    icon: FaSass,
    color: '#CC6699',
  },

  // Backend
  {
    name: 'Node.js',
    level: 80,
    category: 'backend',
    icon: SiNodedotjs,
    color: '#339933',
  },
  {
    name: 'Express.js',
    level: 75,
    category: 'backend',
    icon: SiExpress,
    color: '#000000',
  },
  {
    name: 'MongoDB',
    level: 70,
    category: 'backend',
    icon: SiMongodb,
    color: '#47A248',
  },
  {
    name: 'PostgreSQL',
    level: 70,
    category: 'backend',
    icon: SiPostgresql,
    color: '#4169E1',
  },

  // Tools
  {
    name: 'Git',
    level: 90,
    category: 'tools',
    icon: SiGit,
    color: '#F05032',
  },
  {
    name: 'GitHub',
    level: 90,
    category: 'tools',
    icon: SiGithub,
    color: '#181717',
  },
  {
    name: 'Jest',
    level: 80,
    category: 'tools',
    icon: SiJest,
    color: '#C21325',
  },
  {
    name: 'Figma',
    level: 75,
    category: 'tools',
    icon: SiFigma,
    color: '#F24E1E',
  },
  {
    name: 'Docker',
    level: 70,
    category: 'tools',
    icon: SiDocker,
    color: '#2496ED',
  },
  {
    name: 'Jira',
    level: 85,
    category: 'tools',
    icon: SiJira,
    color: '#0052CC',
  },

  // Methodologies
  {
    name: 'Agile/Scrum',
    level: 90,
    category: 'methodologies',
  },
  {
    name: 'REST API',
    level: 85,
    category: 'methodologies',
  },
  {
    name: 'CI/CD',
    level: 80,
    category: 'methodologies',
  },
  {
    name: 'TDD',
    level: 75,
    category: 'methodologies',
  },
];

export const CONTACT_INFO: ContactInfo = {
  email: 'h.charafi@gmail.com',
  phone: '+33 6 30 47 10 42',
  location: 'Paris, France',
  availability: 'Open to opportunities',
};
